# Generated by Django 5.2.17 on 2026-09-03 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('LOBBY', 'Lobby'), ('WORD_REVEAL', 'Word Reveal'), ('CLUE', 'Clue'), ('VOTING', 'Voting'), ('RESULT', 'Result'), ('GAME_OVER', 'Game Over')], default='LOBBY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='rooms.room')),
            ],
        ),
    ]
