# Generated by Django 5.2.17 on 2026-09-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_wordpair_playerword'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.player'),
        ),
    ]
